branch-defaults:
  main:
    environment: game-master-env
    group_suffix: null
environment-defaults:
  game-master-env:
    branch: null
    repository: null
global:
  application_name: game-master-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
